import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { createApp } from '../../app.js';
import { InMemoryProductRepository } from '../product/in-memory-product.repository.js';
import type { Product } from '../product/product.types.js';

const product: Product = { id: '60000000-0000-4000-8000-000000000001', name: 'Lavender', slug: 'lavender', description: 'Tanaman aromatik pilihan.', price: 125000, stock: 8, imageUrl: null, categoryId: '60000000-0000-4000-8000-000000000002', categoryName: 'Herbal', careLevel: 'MEDIUM', lightRequirement: 'Terang', wateringFrequency: 'Dua kali seminggu', isActive: true, createdAt: new Date(), updatedAt: new Date() };
async function setup() { const app = createApp({ productRepository: new InMemoryProductRepository([product]), authSecret: 'order-test-secret' }); const login = await request(app).post('/api/auth/login').send({ identity: 'customer', password: 'Customer123!' }); return { app, token: login.body.data.token as string }; }
const checkout = { recipientName: 'Customer Demo', phone: '081234567890', shippingAddress: 'Jalan Botani Nomor 10, Jakarta' };

describe('Order checkout API', () => {
  it('membuat pesanan DRAFT dari keranjang dan mengosongkannya', async () => { const { app, token } = await setup(); await request(app).post('/api/cart/items').set('Authorization', `Bearer ${token}`).send({ productId: product.id, quantity: 2 }); const response = await request(app).post('/api/orders').set('Authorization', `Bearer ${token}`).send(checkout); expect(response.status).toBe(201); expect(response.body.data).toMatchObject({ status: 'DRAFT', totalAmount: 250000, recipientName: checkout.recipientName }); expect(response.body.data.items[0]).toMatchObject({ productName: 'Lavender', unitPrice: 125000, quantity: 2, subtotal: 250000 }); const cart = await request(app).get('/api/cart').set('Authorization', `Bearer ${token}`); expect(cart.body.data.items).toHaveLength(0); });
  it('menolak checkout dengan keranjang kosong', async () => { const { app, token } = await setup(); const response = await request(app).post('/api/orders').set('Authorization', `Bearer ${token}`).send(checkout); expect(response.status).toBe(409); expect(response.body.message).toContain('kosong'); });
  it('menolak data penerima yang tidak valid', async () => { const { app, token } = await setup(); const response = await request(app).post('/api/orders').set('Authorization', `Bearer ${token}`).send({ recipientName: 'A', phone: '12', shippingAddress: 'Pendek' }); expect(response.status).toBe(422); expect(response.body.errors).toHaveLength(3); });
  it('mengambil detail pesanan menggunakan nomor pesanan', async () => { const { app, token } = await setup(); await request(app).post('/api/cart/items').set('Authorization', `Bearer ${token}`).send({ productId: product.id, quantity: 1 }); const created = await request(app).post('/api/orders').set('Authorization', `Bearer ${token}`).send(checkout); const detail = await request(app).get(`/api/orders/number/${created.body.data.orderNumber}`).set('Authorization', `Bearer ${token}`); expect(detail.status).toBe(200); expect(detail.body.data.id).toBe(created.body.data.id); });
  it('admin menjalankan transisi valid dan API menolak transisi ilegal', async () => { const { app, token } = await setup(); await request(app).post('/api/cart/items').set('Authorization', `Bearer ${token}`).send({ productId: product.id, quantity: 1 }); const created = await request(app).post('/api/orders').set('Authorization', `Bearer ${token}`).send(checkout); const adminLogin = await request(app).post('/api/auth/login').send({ identity: 'admin', password: 'Admin123!' }); const adminToken = adminLogin.body.data.token as string; const confirmed = await request(app).patch(`/api/admin/orders/${created.body.data.id}/status`).set('Authorization', `Bearer ${adminToken}`).send({ status: 'CONFIRMED' }); expect(confirmed.status).toBe(200); expect(confirmed.body.data.status).toBe('CONFIRMED'); const illegal = await request(app).patch(`/api/admin/orders/${created.body.data.id}/status`).set('Authorization', `Bearer ${adminToken}`).send({ status: 'DRAFT' }); expect(illegal.status).toBe(409); });
  it('customer tidak dapat membuka endpoint manajemen admin', async () => { const { app, token } = await setup(); expect((await request(app).get('/api/admin/orders').set('Authorization', `Bearer ${token}`)).status).toBe(403); });
});
