import { useEffect, useState } from 'react';
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Cart } from '../features/products/product.types';
import { useAuthStore } from '../features/auth/auth.store';
import { apiRequest } from '../services/api';

export function CartPage() {
  const token = useAuthStore((state) => state.token)!; const [cart, setCart] = useState<Cart | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  useEffect(() => { apiRequest<Cart>('/cart', {}, token).then(setCart).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Keranjang gagal dimuat.')); }, [token]);
  async function change(itemId: string, quantity: number) { setBusy(itemId); setError(''); try { setCart(await apiRequest<Cart>(`/cart/items/${itemId}`, { method: 'PATCH', body: JSON.stringify({ quantity }) }, token)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Jumlah gagal diperbarui.'); } finally { setBusy(''); } }
  async function remove(itemId: string) { setBusy(itemId); setError(''); try { setCart(await apiRequest<Cart>(`/cart/items/${itemId}`, { method: 'DELETE' }, token)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Item gagal dihapus.'); } finally { setBusy(''); } }
  if (!cart && !error) return <main className="container-shell py-16"><div className="skeleton h-80 rounded-[2rem]" /></main>;
  return <main className="container-shell py-12 sm:py-16"><p className="section-kicker">Keranjang</p><h1 className="section-title">Pilihan hijaumu.</h1>{error && <div role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{cart?.items.length === 0 && <div className="panel mt-8 grid min-h-72 place-items-center p-8 text-center"><div><ShoppingBag className="mx-auto text-leaf-600" size={34} /><h2 className="mt-4 font-display text-2xl font-semibold">Keranjang masih kosong</h2><Link to="/products" className="button-base button-primary mt-6 px-5 py-3">Jelajahi katalog</Link></div></div>}{cart && cart.items.length > 0 && <div className="mt-8 grid gap-7 lg:grid-cols-[1fr_22rem]"><section className="space-y-4">{cart.items.map((item) => <article key={item.id} className="panel flex flex-col gap-5 p-5 sm:flex-row sm:items-center"><div className="grid size-24 shrink-0 place-items-center rounded-2xl bg-sage-100 text-leaf-600"><ShoppingBag /></div><div className="min-w-0 flex-1"><Link to={`/products/${item.product.slug}`} className="font-display text-xl font-semibold text-forest-950">{item.product.name}</Link><p className="mt-1 text-sm text-slate-500">{rupiah(item.product.price)} · stok {item.product.stock}</p><p className="mt-3 font-bold text-forest-900">{rupiah(item.subtotal)}</p></div><div className="flex items-center gap-2"><button aria-label={`Kurangi ${item.product.name}`} className="icon-button border border-sage-200" disabled={busy === item.id || item.quantity <= 1} onClick={() => change(item.id, item.quantity - 1)}><Minus size={15} /></button><span className="w-7 text-center font-bold">{item.quantity}</span><button aria-label={`Tambah ${item.product.name}`} className="icon-button border border-sage-200" disabled={busy === item.id || item.quantity >= Math.min(10, item.product.stock)} onClick={() => change(item.id, item.quantity + 1)}><Plus size={15} /></button><button aria-label={`Hapus ${item.product.name}`} className="icon-button text-red-600" disabled={busy === item.id} onClick={() => remove(item.id)}><Trash2 size={17} /></button></div></article>)}</section><aside className="panel h-fit p-6"><h2 className="font-display text-2xl font-semibold text-forest-950">Ringkasan</h2><div className="mt-6 flex justify-between text-sm text-slate-600"><span>{cart.totalQuantity} item</span><span>{rupiah(cart.total)}</span></div><div className="mt-4 flex justify-between border-t border-sage-200 pt-4 font-bold text-forest-950"><span>Total</span><span>{rupiah(cart.total)}</span></div><Link to="/checkout" className="button-base button-primary mt-6 w-full px-5 py-3">Lanjut checkout</Link></aside></div>}</main>;
}
function rupiah(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }
