import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowLeft, CheckCircle2, MapPin, PackageCheck, Phone, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import type { Cart, Order } from '../features/products/product.types';
import { useAuthStore } from '../features/auth/auth.store';
import { ApiError, apiRequest } from '../services/api';

export function CheckoutPage() {
  const navigate = useNavigate(); const { token, user } = useAuthStore(); const [cart, setCart] = useState<Cart | null>(null); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [form, setForm] = useState({ recipientName: user?.name ?? '', phone: '', shippingAddress: '' });
  useEffect(() => { if (token) apiRequest<Cart>('/cart', {}, token).then(setCart).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Keranjang gagal dimuat.')); }, [token]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!token) return; setSubmitting(true); setError(''); setFieldErrors({}); try { const order = await apiRequest<Order>('/orders', { method: 'POST', body: JSON.stringify(form) }, token); navigate(`/orders/${order.orderNumber}`, { state: { order }, replace: true }); } catch (reason) { if (reason instanceof ApiError) { setError(reason.message); setFieldErrors(Object.fromEntries((reason.errors ?? []).map((item) => [item.field, item.message]))); } else setError('Checkout gagal diproses.'); } finally { setSubmitting(false); } }
  if (!cart && !error) return <main className="container-shell py-16"><div className="skeleton h-[30rem] rounded-[2rem]" /></main>;
  if (cart?.items.length === 0) return <main className="container-shell py-16"><div className="panel p-10 text-center"><PackageCheck className="mx-auto text-leaf-600" /><h1 className="mt-4 font-display text-2xl font-semibold">Keranjang kosong</h1><Link to="/products" className="button-base button-primary mt-6 px-5 py-3">Pilih produk</Link></div></main>;
  return <main className="container-shell py-12 sm:py-16"><Link to="/cart" className="inline-flex items-center gap-2 text-sm font-semibold text-forest-800"><ArrowLeft size={17} /> Kembali ke keranjang</Link><div className="mt-7 grid gap-7 lg:grid-cols-[1fr_24rem]"><section><p className="section-kicker">Checkout aman</p><h1 className="section-title">Data penerima.</h1><form onSubmit={submit} className="panel mt-7 grid gap-5 p-6 sm:p-8"><Field label="Nama penerima" icon={<UserRound size={18} />} error={fieldErrors.recipientName}><input value={form.recipientName} onChange={(event) => setForm({ ...form, recipientName: event.target.value })} placeholder="Nama lengkap" /></Field><Field label="Nomor telepon" icon={<Phone size={18} />} error={fieldErrors.phone}><input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="0812 3456 7890" /></Field><label className="field-label">Alamat pengiriman<div className="flex gap-3 rounded-[.9rem] border border-sage-200 bg-sage-50 p-4 text-slate-500"><MapPin size={18} className="shrink-0" /><textarea className="min-h-28 w-full resize-y border-0 bg-transparent text-sm text-forest-900 outline-none" value={form.shippingAddress} onChange={(event) => setForm({ ...form, shippingAddress: event.target.value })} placeholder="Jalan, nomor rumah, kecamatan, kota, kode pos" /></div>{fieldErrors.shippingAddress && <span className="field-error">{fieldErrors.shippingAddress}</span>}</label>{error && <div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<button className="button-base button-primary h-13 px-6" disabled={submitting}><CheckCircle2 size={18} /> {submitting ? 'Memproses…' : 'Konfirmasi pesanan'}</button></form></section><aside className="panel h-fit p-6"><h2 className="font-display text-2xl font-semibold text-forest-950">Ringkasan</h2><div className="mt-5 space-y-4">{cart?.items.map((item) => <div key={item.id} className="flex justify-between gap-4 text-sm"><span className="text-slate-600">{item.quantity}× {item.product.name}</span><span className="font-semibold">{rupiah(item.subtotal)}</span></div>)}</div><div className="mt-5 flex justify-between border-t border-sage-200 pt-5 font-bold"><span>Total</span><span>{rupiah(cart?.total ?? 0)}</span></div><p className="mt-5 text-xs leading-5 text-slate-500">Stok diperiksa kembali saat konfirmasi. Pembayaran disimulasikan sesuai ruang lingkup UTS.</p></aside></div></main>;
}
function Field({ label, icon, error, children }: { label: string; icon: React.ReactNode; error?: string; children: React.ReactNode }) { return <label className="field-label">{label}<div className="field-shell">{icon}{children}</div>{error && <span className="field-error">{error}</span>}</label>; }
function rupiah(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }
